name: "Pull Request Labeler"
on:
  workflow_dispatch:

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
    - name: Label the PR
      uses: gerrymanoim/pr-prefix-labeler@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}